if(!exists("baseDir")) baseDir <- dirname(dirname(getwd()))
source(file.path(baseDir,"MRIwithR","book_init.R"))
if(!dir.exists(baseDir)) stop("please define baseDir")
IRdataDir <- file.path(baseDir,"MRIwithRdata","IR")
IRresDir <- file.path(baseDir,"MRIwithRresults","IR")
if(!dir.exists(IRresDir)) dir.create(IRresDir)
IRT1Dir <- file.path(IRresDir,"T1")
if(!dir.exists(IRT1Dir)) dir.create(file.path(IRresDir,"T1"))
library(qMRI)
library(adimpro)
library(aws)
library(kirby21.t1)
haveFSLr <- require(fslr)
library(oro.nifti)
library(stringr)